version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  builder: dirhtml
  configuration: docs/conf.py

formats:
  - pdf

python:
  install:
  - requirements: docs/requirements.txt
