plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
title: Tiled
url: https://www.mapeditor.org
repository: mapeditor/tiled
twitter:
  username: TiledApp
include:
  - .well-known
exclude:
  - docs/typedoc_theme
