// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KARCHIVE_VERSION_H
#define KARCHIVE_VERSION_H

#define KARCHIVE_VERSION_STRING "6.21.0"
#define KARCHIVE_VERSION_MAJOR 6
#define KARCHIVE_VERSION_MINOR 21
#define KARCHIVE_VERSION_PATCH 0
#define KARCHIVE_VERSION ((6<<16)|(21<<8)|(0))

#endif
