name: Feature request
description: Suggest an idea for this project
type: Feature

body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated, when…
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
      placeholder: Instead of behaving like this, there should be…
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Another solution that would work, is…
    validations:
      required: false
