.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "AUTOMAPPINGCONVERTER" "1" "July 2013" "" ""
.
.SH "NAME"
\fBautomappingconverter\fR \- a converter for old tiled automapping rules
.
.SH "SYNOPSIS"
\fBautomappingconverter\fR
.
.SH "DESCRIPTION"
This converter is used to convert automapping rules of The Tiled Mapeditor from version 0\.8\.x and lower to 0\.9\.0 and later\.
.
.SH "AUTHORS"
\fIhttps://github\.com/bjorn/tiled/blob/master/AUTHORS\fR
.
.SH "SEE ALSO"
tiled(1), \fIhttp://www\.mapeditor\.org/\fR, \fIhttps://github\.com/bjorn/tiled/wiki/Automapping#wiki\-Converting_rules_from_08_and_below\fR
