.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TILED" "1" "January 2013" "" ""
.
.SH "NAME"
\fBtiled\fR \- tile map editor
.
.SH "SYNOPSIS"
\fBtiled\fR [\fIOPTIONS\fR] [FILES\.\.\.]
.
.SH "DESCRIPTION"
Tiled is a general purpose tile map editor\. It\'s built to be easy to use, yet flexible enough to work with varying game engines, whether your game is an RPG, platformer or Breakout clone\. Tiled is free software and written in C++, using the Qt application framework\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR \fB\-\-help\fR
Displays the help
.
.TP
\fB\-v\fR \fB\-\-version\fR
Displays the version
.
.TP
\fB\-\-quit\fR
Only check validity of arguments
.
.TP
\fB\-\-disable\-opengl\fR
Disables hardware accelerated rendering
.
.SH "AUTHORS"
\fIhttps://github\.com/bjorn/tiled/blob/master/AUTHORS\fR
.
.SH "SEE ALSO"
tmxviewer(1), tmxrasterizer(1), \fIhttp://www\.mapeditor\.org/\fR
