.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TMXVIEWER" "1" "January 2013" "" ""
.
.SH "NAME"
\fBtmxviewer\fR \- a simple tile map viewer
.
.SH "SYNOPSIS"
\fBtmxviewer\fR [\fIOPTIONS\fR] [FILES\.\.\.]
.
.SH "DESCRIPTION"
This application can be used to quickly view a map that was created by the Tiled Map Editor\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR \fB\-\-help\fR
Displays the help
.
.TP
\fB\-v\fR \fB\-\-version\fR
Displays the version
.
.SH "AUTHORS"
\fIhttps://github\.com/bjorn/tiled/blob/master/AUTHORS\fR
.
.SH "SEE ALSO"
tiled(1), tmxrasterizer(1), \fIhttp://www\.mapeditor\.org/\fR
