/*
 * GMX Tiled Plugin
 * Copyright 2016, Jones Blunt <mrjonesblunt@gmail.com>
 *
 * This file is part of Tiled.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include "gmxplugin.h"

#include "map.h"
#include "tile.h"
#include "tilelayer.h"
#include "mapobject.h"
#include "objectgroup.h"

#include <QDir>
#include <QFileInfo>
#include <QSaveFile>
#include <QXmlStreamWriter>

using namespace Tiled;
using namespace Gmx;

GmxPlugin::GmxPlugin()
{
}

bool GmxPlugin::write(const Map *map, const QString &fileName)
{
    QSaveFile file(fileName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        mError = tr("Could not open file for writing.");
        return false;
    }

    QXmlStreamWriter stream(&file);

    stream.setAutoFormatting(true);
    stream.setAutoFormattingIndent(2);

    stream.writeComment("This Document is generated by Tiled, if you edit it by hand then you do so at your own risk!");

    stream.writeStartElement("room");

    stream.writeTextElement("width", QString::number(map->tileWidth() * map->width()));
    stream.writeTextElement("height", QString::number(map->tileHeight() * map->height()));

    stream.writeTextElement("isometric", QString::number((map->orientation() == Map::Orientation::Isometric ? 1 : 0)));

    stream.writeStartElement("instances");

    for (const Layer *layer : map->layers()) {

        if (layer->layerType() != Layer::ObjectGroupType) continue;
        const ObjectGroup *objectLayer = static_cast<const ObjectGroup*>(layer);

        for (const MapObject *object : objectLayer->objects()) {

            stream.writeStartElement("instance");

            stream.writeAttribute("objName", object->name());

            if(object->rotation() != 0) {
                QPoint base(0, object->height());
                base = QTransform().rotate(-object->rotation()).map(base);

                stream.writeAttribute("x", QString::number((int)(object->x()) + base.x()));
                stream.writeAttribute("y", QString::number((int)(object->y()) - base.y()));
                stream.writeAttribute("rotation", QString::number(-object->rotation()));
            } else {
                stream.writeAttribute("x", QString::number((int)(object->x())));
                stream.writeAttribute("y", QString::number((int)(object->y() - object->height())));
            }

            stream.writeAttribute("id", QString::number(object->id()));

            stream.writeEndElement();
        }
    }

    stream.writeEndElement();


    stream.writeStartElement("tiles");



    uint tileId = 0u;
    int currentLayer = map->layers().size();
    for (const Layer *layer : map->layers()) {

        if (layer->layerType() != Layer::TileLayerType) continue;

        QString depth = QString::number(layer->hasProperty(QLatin1String("Depth")) ? layer->property(QLatin1String("Depth")).toInt() : currentLayer);

        const TileLayer *tileLayer = static_cast<const TileLayer*>(layer);
        for (int y = 0; y < tileLayer->height(); ++y) {
            for (int x = 0; x < tileLayer->width(); ++x) {
                const Cell &cell = tileLayer->cellAt(x, y);
                const Tile *tile = cell.tile;
                if(tile) {
                    stream.writeStartElement("tile");

                    stream.writeAttribute("bgName", tile->tileset()->name());
                    stream.writeAttribute("x", QString::number((int)(x * map->tileWidth())));
                    stream.writeAttribute("y", QString::number((int)(y * map->tileHeight())));
                    stream.writeAttribute("w", QString::number(tile->width()));
                    stream.writeAttribute("h", QString::number(tile->height()));

                    stream.writeAttribute("xo", QString::number(tile->id() % tile->tileset()->columnCount() * tile->tileset()->tileWidth()));
                    stream.writeAttribute("yo", QString::number((int)(tile->id() / tile->tileset()->columnCount()) * tile->tileset()->tileWidth()));

                    stream.writeAttribute("depth", depth);
                    stream.writeAttribute("id", QString::number(++tileId));

                    stream.writeEndElement();
                }
            }
        }

        currentLayer--;
    }

    stream.writeEndElement();
    stream.writeEndDocument();

    if (!file.commit()) {
        mError = file.errorString();
        return false;
    }

    return true;
}

QString GmxPlugin::errorString() const
{
    return mError;
}


QString GmxPlugin::nameFilter() const
{
    return tr("GameMaker room files (*.room.gmx)");
}
