name: tiled
adopt-info: tiled
license: GPL-2.0
base: core24

grade: stable
confinement: strict
environment:
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins"

apps:
  tiled:
    command: usr/bin/tiled
    common-id: org.mapeditor.Tiled.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
      - opengl
      - network
  tmxviewer:
    command: usr/bin/tmxviewer
    plugs: &basic-plugs
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
  tmxrasterizer:
    command: usr/bin/tmxrasterizer
    plugs: *basic-plugs
  terraingenerator:
    command: usr/bin/terraingenerator
    plugs: *basic-plugs

parts:
  tiled:
    plugin: make
    override-pull: |
      craftctl default
      craftctl set version="$(git describe | sed 's/v//')"
    override-build: |
      qbs setup-toolchains --detect
      qbs setup-qt /usr/bin/qmake6 qt6
      qbs config defaultProfile qt6
      qbs build --jobs "${CRAFT_PARALLEL_BUILD_COUNT}" --command-echo-mode command-line config:release qbs.installPrefix:"/usr" projects.Tiled.version:$(craftctl get version) projects.Tiled.useRPaths:false
      qbs install --install-root "${CRAFT_PART_INSTALL}" config:release
    parse-info:
      - usr/share/metainfo/org.mapeditor.Tiled.appdata.xml
    source: .
    build-packages:
      - build-essential
      - libzstd-dev
      - pkg-config
      - qbs
      - qt6-base-dev
      - qt6-declarative-dev
      - qt6-l10n-tools
      - qt6-svg-dev
      - zlib1g-dev
    # FIXME: Python plugin compiles and loads, but can't find platform libraries
    #  - python-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fcitx-frontend-qt6
      - libgdk-pixbuf2.0-0
      - libqt6concurrent6t64
      - libqt6gui6t64
      - libqt6openglwidgets6t64
      - libqt6quick6
      - libqt6svg6 # for loading icons which are svg
      - libqt6widgets6t64
      - libxkbcommon0
      - libzstd1
      - xkb-data
      - light-themes
      - locales-all
      - qt6-image-formats-plugins
      - qt6-wayland
      - shared-mime-info
      - xdg-user-dirs
      #- libpython2.7

  qaseprite:
    source: https://github.com/mapeditor/qaseprite/releases/download/1.0/qaseprite-1.0-source.tar.gz
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_SHARED_ZLIB=on
      - -DUSE_SHARED_LIBPNG=on
      - -DUSE_SHARED_PIXMAN=on
      - -DUSE_SHARED_FREETYPE=on
      - -DUSE_SHARED_HARFBUZZ=on
    build-packages:
      - libfreetype-dev
      - libgl1-mesa-dev
      - libharfbuzz-dev
      - libpixman-1-dev
      - libxcursor-dev
      - libxi-dev
      - zlib1g-dev
    stage-packages:
      - libfreetype6
      - libharfbuzz0b
      - libpixman-1-0
      - libxcursor1
      - libxi6
      - zlib1g

